import Config

#
#
# Mnesia config
config :mnesia,
  dir: ~c"/db"

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :obr_web, ObrWeb.Endpoint,
  url: [host: "example.com", port: 4000],
  cache_static_manifest: "priv/static/cache_manifest.json"

config :obr_mgmt_web, ObrMgmtWeb.Endpoint,
  url: [host: "example.com", port: 4400],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
